# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schapen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intern_nummer', models.CharField(max_length=50)),
                ('geslacht', models.IntegerField(choices=[(1, 'Ram'), (2, 'Ooi')])),
                ('geboortedatum', models.DateTimeField()),
                ('einddatum', models.DateTimeField()),
                ('Sanitel', models.CharField(max_length=11)),
            ],
        ),
    ]
