# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schapen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schapen',
            name='einddatum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schapen',
            name='geboortedatum',
            field=models.DateField(blank=True, null=True),
        ),
    ]
