# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schapen', '0002_auto_20170105_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='schapen',
            name='moeder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ooi_lam', to='schapen.Schapen'),
        ),
        migrations.AddField(
            model_name='schapen',
            name='vader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ram_lam', to='schapen.Schapen'),
        ),
    ]
